version: "3"

services:
  neard:
    build:
      context: ./
      dockerfile: nearup.Dockerfile
    volumes:
      - ./.near:/root/.near
      - ./.nearup:/root/.nearup
    ports:
      - "3030:3030"
    command: run localnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/status"]
      interval: 30s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: localnear
      POSTGRES_PASSWORD: localnear
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
  # near-indexer-for-explorer:
    # image: nearprotocol/near-indexer-for-explorer:mhala-docker
    # restart: always
    # volumes:
      # - ./.near-indexer:/root/.near
    # environment:
      # DATABASE_URL: postgres://localnear:localnear@postgres/indexer
    # depends_on:
      # neard:
        # condition: service_healthy
      # postgres:
        # condition: service_healthy
volumes:
  postgres: ~
