version: "3"

# https://github.com/near/docs/blob/975642ad49338bf8728a675def1f8bec8a780922/docs/local-setup/entire-setup.md
# https://github.com/kurtosis-tech/near-kurtosis-module/tree/develop/kurtosis-module/impl/services

services:
  neard:
    build:
      context: ./nearup
      args:
        - VERSION=1.26.0/c164b7df5f94f54c8f36305348dcd9f9b9994ddc
    volumes:
      - ./.near:/root/.near
      - ./.nearup:/root/.nearup
    ports:
      - "3030:3030"
    command: run localnet --num-nodes 1 --num-shards 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/status"]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: localnear
      POSTGRES_PASSWORD: localnear
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localnear"]
      interval: 5s
      timeout: 5s
      retries: 5
  indexer:
    image: kurtosistech/near-indexer-for-explorer:7510e7f
    volumes:
      - ./.near-indexer:/root/.near
    environment:
      DATABASE_URL: postgres://localnear:localnear@postgres/indexer
    depends_on:
      neard:
        condition: service_healthy
      postgres:
        condition: service_healthy
  contract-helper:
    build:
      context: ./contract-helper
    environment:
      MAIL_HOST: "smtp.ethereal.email"
      MAIL_PASSWORD: ""
      MAIL_PORT: "587"
      MAIL_USER: ""
      NEW_ACCOUNT_AMOUNT: "10000000000000000000000000"
      NODE_ENV: "development"
      NEAR_WALLET_ENV: "development"
      PORT: 3032
      TWILIO_ACCOUNT_SID: ""
      TWILIO_AUTH_TOKEN: ""
      TWILIO_FROM_PHONE: "+14086179592"
      WALLET_URL: ""
      INDEXER_DB_CONNECTION: "postgres://localnear:localnear@postgres/indexer"
      NODE_URL: "http://neard:3030"
    depends_on:
      neard:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./.near:/root/.near:ro
    ports:
      - "3032:3032"
  wallet:
    build:
      context: ./wallet
    depends_on:
      neard:
        condition: service_healthy
    ports:
      - "3004:3004"
volumes:
  postgres: ~
