version: "3"

# https://github.com/kurtosis-tech/near-kurtosis-module/tree/develop/kurtosis-module/impl/services

services:
  neard:
    build:
      context: ./
      dockerfile: nearup.Dockerfile
    volumes:
      - ./.near:/root/.near
      - ./.nearup:/root/.nearup
    ports:
      - "3030:3030"
    command: run localnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/status"]
      interval: 30s
      timeout: 5s
      retries: 5
  postgres:
    build:
      context: ./
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: localnear
      POSTGRES_PASSWORD: localnear
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
  near-indexer-for-explorer:
    image: kurtosistech/near-indexer-for-explorer:7510e7f
    restart: always
    volumes:
      - ./.near-indexer:/root/.near
    environment:
      DATABASE_URL: postgres://localnear:localnear@postgres/indexer
    depends_on:
      neard:
        condition: service_healthy
      postgres:
        condition: service_healthy
  contract-helper:
    build:
      context: ./
      dockerfile: contract-helper.Dockerfile
    environment:
      MAIL_HOST: "smtp.ethereal.email"
      MAIL_PASSWORD: ""
      MAIL_PORT: "587"
      MAIL_USER: ""
      NEW_ACCOUNT_AMOUNT: "10000000000000000000000000"
      NODE_ENV: "development"
      NEAR_WALLET_ENV: "development"
      PORT: 3032
      TWILIO_ACCOUNT_SID: ""
      TWILIO_AUTH_TOKEN: ""
      TWILIO_FROM_PHONE: "+14086179592"
      WALLET_URL: ""
      INDEXER_DB_CONNECTION: "postgres://localnear:localnear@postgres/accounts"
      NODE_URL: "http://neard:3030"
    depends_on:
      neard:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./.near:/root/.near
    ports:
      - "3032:3032"
  near-wallet:
    build:
      context: ./
      dockerfile: wallet.Dockerfile
    restart: always
    depends_on:
      neard:
        condition: service_healthy
    ports:
      - "3004:3004"
volumes:
  postgres: ~
